import os
import requests
import logging
from datetime import datetime
from core.config import (
    AZURE_CLIENT_ID, 
    AZURE_CLIENT_SECRET, 
    AZURE_TENANT_ID, 
    AZURE_SENDER_EMAIL
)

logger = logging.getLogger("pipelyt.email")

class EmailService:
    def __init__(self):
        self.client_id = AZURE_CLIENT_ID
        self.client_secret = AZURE_CLIENT_SECRET
        self.tenant_id = AZURE_TENANT_ID
        self.sender_email = AZURE_SENDER_EMAIL
        self.token = None
        self.token_expires_at = None

    def _get_access_token(self):
        """Authenticates with Azure AD and retrieves a Microsoft Graph access token."""
        # Check if token is still valid
        if self.token and self.token_expires_at > datetime.now().timestamp():
            return self.token

        url = f"https://login.microsoftonline.com/{self.tenant_id}/oauth2/v2.0/token"
        data = {
            "client_id": self.client_id,
            "scope": "https://graph.microsoft.com/.default",
            "client_secret": self.client_secret,
            "grant_type": "client_credentials"
        }
        
        try:
            response = requests.post(url, data=data)
            response.raise_for_status()
            res_data = response.json()
            
            self.token = res_data["access_token"]
            # Set expiry with a small buffer
            self.token_expires_at = datetime.now().timestamp() + res_data["expires_in"] - 60
            return self.token
        except Exception as e:
            logger.error(f"Failed to get Azure access token: {e}")
            return None

    def send_otp_email(self, recipient_email, otp_code, purpose="verification"):
        """Sends an OTP email via Microsoft Graph API."""
        token = self._get_access_token()
        if not token:
            return False

        url = f"https://graph.microsoft.com/v1.0/users/{self.sender_email}/sendMail"
        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json"
        }

        subject = "Your Pipelyt Verification Code"
        if purpose == "register":
            subject = "Pipelyt - Create Your Account"
        elif purpose == "reset_password":
            subject = "Pipelyt - Password Reset Code"

        email_body = f"""
        <html>
            <body style="font-family: Arial, sans-serif; color: #333;">
                <div style="max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
                    <h2 style="color: #FF6B35;">Verification Required</h2>
                    <p>Hello,</p>
                    <p>Use the following code to complete your {purpose.replace('_', ' ')}:</p>
                    <div style="background: #fdf2f0; padding: 15px; border-radius: 8px; text-align: center; margin: 20px 0;">
                        <span style="font-size: 32px; font-weight: bold; color: #FF6B35; letter-spacing: 5px;">{otp_code}</span>
                    </div>
                    <p style="font-size: 14px; color: #666;">This code will expire in 10 minutes. If you did not request this code, please ignore this email.</p>
                    <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                    <p style="font-size: 12px; color: #999;">&copy; 2026 Pipelyt AI. All rights reserved.</p>
                </div>
            </body>
        </html>
        """

        payload = {
            "message": {
                "subject": subject,
                "body": {
                    "contentType": "HTML",
                    "content": email_body
                },
                "toRecipients": [
                    {
                        "emailAddress": {
                            "address": recipient_email
                        }
                    }
                ]
            }
        }

        try:
            response = requests.post(url, headers=headers, json=payload)
            response.raise_for_status()
            logger.info(f"OTP email sent successfully to {recipient_email}")
            return True
        except Exception as e:
            logger.error(f"Failed to send OTP email via Microsoft Graph: {e}")
            if hasattr(e, 'response') and e.response:
                logger.error(f"Graph Error: {e.response.text}")
            return False

    def send_team_invite_email(self, recipient_email, inviter_name, company_name,
                                brand_name, accept_url):
        """Send a team-members invitation email with the accept-link.

        The URL is generated by the caller from FRONTEND_URL + /accept-invite
        + ?token=... so this method doesn't need to know the frontend host.
        """
        token = self._get_access_token()
        if not token:
            return False

        url = f"https://graph.microsoft.com/v1.0/users/{self.sender_email}/sendMail"
        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        }

        subject = f"{inviter_name or company_name or 'Pipelyt'} invited you to Pipelyt"
        email_body = f"""
        <html>
            <body style="font-family: Arial, sans-serif; color: #333;">
                <div style="max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
                    <h2 style="color: #FF6B35;">You're invited to Pipelyt</h2>
                    <p>Hello,</p>
                    <p><strong>{inviter_name or 'An admin'}</strong>{f" from <strong>{company_name}</strong>" if company_name else ''} has invited you to join their Pipelyt workspace as a team member{f" for the <strong>{brand_name}</strong> brand" if brand_name else ''}.</p>
                    <p>Click the button below to set your password and finish creating your account.</p>
                    <div style="text-align: center; margin: 28px 0;">
                        <a href="{accept_url}" style="background: #FF6B35; color: #fff; text-decoration: none; padding: 14px 28px; border-radius: 10px; font-weight: bold; display: inline-block;">Accept Invitation</a>
                    </div>
                    <p style="font-size: 13px; color: #666;">Or copy this link into your browser:<br/>
                        <span style="word-break: break-all; color: #FF6B35;">{accept_url}</span>
                    </p>
                    <p style="font-size: 13px; color: #666;">This link is single-use and expires in 7 days. If you weren't expecting this invitation, you can safely ignore it.</p>
                    <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                    <p style="font-size: 12px; color: #999;">&copy; 2026 Pipelyt AI. All rights reserved.</p>
                </div>
            </body>
        </html>
        """

        payload = {
            "message": {
                "subject": subject,
                "body": {"contentType": "HTML", "content": email_body},
                "toRecipients": [{"emailAddress": {"address": recipient_email}}],
            }
        }
        try:
            response = requests.post(url, headers=headers, json=payload)
            response.raise_for_status()
            logger.info(f"Team invite email sent to {recipient_email}")
            return True
        except Exception as e:
            logger.error(f"Failed to send team invite email: {e}")
            if hasattr(e, 'response') and e.response:
                logger.error(f"Graph Error: {e.response.text}")
            return False


    def send_reconnect_request_email(self, admin_email, member_name,
                                       platform, account_name, reason=""):
        """Notify the admin that a team member has requested reconnect of a
        social account."""
        token = self._get_access_token()
        if not token:
            return False

        url = f"https://graph.microsoft.com/v1.0/users/{self.sender_email}/sendMail"
        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        }

        platform_display = (platform or "").capitalize() or "Social"
        subject = f"{member_name} needs you to reconnect their {platform_display} account"

        email_body = f"""
        <html>
            <body style="font-family: Arial, sans-serif; color: #333;">
                <div style="max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
                    <h2 style="color: #FF6B35;">Reconnect Requested</h2>
                    <p>Hello,</p>
                    <p><strong>{member_name}</strong> has asked you to refresh their {platform_display} connection
                       ({account_name or 'an account'}) inside Pipelyt.</p>
                    {f'<p style="background:#fdf2f0;padding:10px;border-radius:8px;font-style:italic;">{reason}</p>' if reason else ''}
                    <p>Sign in to Pipelyt and run the OAuth reconnect flow for this account. As soon as
                       the new token lands, the request is automatically closed and your team member can
                       keep publishing.</p>
                    <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                    <p style="font-size: 12px; color: #999;">&copy; 2026 Pipelyt AI. All rights reserved.</p>
                </div>
            </body>
        </html>
        """

        payload = {
            "message": {
                "subject": subject,
                "body": {"contentType": "HTML", "content": email_body},
                "toRecipients": [{"emailAddress": {"address": admin_email}}],
            }
        }
        try:
            response = requests.post(url, headers=headers, json=payload)
            response.raise_for_status()
            logger.info(f"Reconnect-request email sent to {admin_email}")
            return True
        except Exception as e:
            logger.error(f"Failed to send reconnect-request email: {e}")
            if hasattr(e, 'response') and e.response:
                logger.error(f"Graph Error: {e.response.text}")
            return False


    def send_weekly_report_email(self, recipient_email, user_name, stats):
        """Send the weekly dashboard-stats digest.

        `stats` is the dict produced by services/weekly_report.aggregate_user_stats:
        {scheduled_count, published_count, drafts_count, connected_count,
         followers, engagement_rate, upcoming_count}.
        """
        token = self._get_access_token()
        if not token:
            return False

        url = f"https://graph.microsoft.com/v1.0/users/{self.sender_email}/sendMail"
        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        }

        subject = "Your Pipelyt Weekly Report"

        def _card(label, value):
            return f"""
                <td style="width:25%; padding:10px; text-align:center; background:#fdf2f0; border-radius:8px;">
                    <div style="font-size:12px; color:#999; text-transform:uppercase; letter-spacing:0.5px;">{label}</div>
                    <div style="font-size:24px; font-weight:bold; color:#FF6B35; margin-top:6px;">{value}</div>
                </td>
            """

        email_body = f"""
        <html>
            <body style="font-family: Arial, sans-serif; color: #333;">
                <div style="max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
                    <h2 style="color: #FF6B35;">Your Weekly Pipelyt Report</h2>
                    <p>Hello {user_name or 'there'},</p>
                    <p>Here's what happened with your content pipeline this week:</p>

                    <table role="presentation" width="100%" cellspacing="8" cellpadding="0" style="margin: 20px 0; border-collapse: separate;">
                        <tr>
                            {_card("Scheduled Posts", stats.get("scheduled_count", 0))}
                            {_card("Successful Posts", stats.get("published_count", 0))}
                        </tr>
                        <tr>
                            {_card("Saved Drafts", stats.get("drafts_count", 0))}
                            {_card("Connected Accounts", stats.get("connected_count", 0))}
                        </tr>
                    </table>

                    <table role="presentation" width="100%" cellspacing="8" cellpadding="0" style="margin: 20px 0; border-collapse: separate;">
                        <tr>
                            {_card("Followers", stats.get("followers", 0))}
                            {_card("Engagement Rate", stats.get("engagement_rate", "0%"))}
                        </tr>
                    </table>

                    <a href="https://app.pipelyt.ai/" style="display:block; background:#FF6B35; color:#fff; padding:16px; border-radius:10px; text-align:center; margin: 20px 0; text-decoration:none;">
                        <strong>{stats.get("upcoming_count", 0)} posts</strong> ready for flight this week.
                    </a>

                    <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                    <p style="font-size: 12px; color: #999;">&copy; 2026 Pipelyt AI. All rights reserved.</p>
                </div>
            </body>
        </html>
        """

        payload = {
            "message": {
                "subject": subject,
                "body": {"contentType": "HTML", "content": email_body},
                "toRecipients": [{"emailAddress": {"address": recipient_email}}],
            }
        }
        try:
            response = requests.post(url, headers=headers, json=payload)
            response.raise_for_status()
            logger.info(f"Weekly report email sent to {recipient_email}")
            return True
        except Exception as e:
            logger.error(f"Failed to send weekly report email: {e}")
            if hasattr(e, 'response') and e.response:
                logger.error(f"Graph Error: {e.response.text}")
            return False


# Global instance
email_service = EmailService()
