import { AbsoluteFill, Series, useVideoConfig } from 'remotion';
import { LogoIntro } from '../components/LogoIntro';
import { PainAvatar } from '../components/PainAvatar';
import { SolutionAvatar } from '../components/SolutionAvatar';
import { CTACard } from '../components/CTACard';
import type { ReelPromoStoryboard, Scene } from '../storyboard-types';
import { FPS } from '../storyboard-types';

/**
 * Reel Promo composition — v4 character-driven framework.
 *
 *   1. logo_intro       — brand stamp 0–2s
 *   2. pain_avatar      — person struggling, problem text overlay
 *   3. solution_avatar  — different person, solution explanation
 *   4. cta_card         — action close
 *
 * No global animated background here — each scene OWNS its own visual
 * layer (photo or solid + flash). That keeps the energy where the
 * eye is supposed to be.
 */
export const BrandPromo: React.FC<{ storyboard: ReelPromoStoryboard }> = ({ storyboard }) => {
  const { fps } = useVideoConfig();
  const { brand, scenes } = storyboard;

  return (
    <AbsoluteFill>
      <Series>
        {scenes.map((scene, i) => (
          <Series.Sequence
            key={i}
            durationInFrames={Math.round(scene.duration_sec * (fps || FPS))}
          >
            {renderScene(scene, brand)}
          </Series.Sequence>
        ))}
      </Series>
    </AbsoluteFill>
  );
};

const renderScene = (scene: Scene, brand: ReelPromoStoryboard['brand']): React.ReactNode => {
  switch (scene.type) {
    case 'logo_intro':       return <LogoIntro brand={brand} />;
    case 'pain_avatar':      return <PainAvatar scene={scene} brand={brand} />;
    case 'solution_avatar':  return <SolutionAvatar scene={scene} brand={brand} />;
    case 'cta_card':         return <CTACard scene={scene} brand={brand} />;
    default: {
      // Unknown scene type — usually means a stale storyboard JSON
      // generated by an older agent version. Render a minimal brand
      // panel instead of returning null, because Series.Sequence
      // refuses to mount with no children and crashes the entire video.
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const _exhaustive: any = scene;
      return (
        <AbsoluteFill
          style={{
            background: brand.background_color || '#0f172a',
            color: brand.text_color || '#ffffff',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            fontFamily: 'sans-serif',
            fontSize: 48,
            padding: 64,
            textAlign: 'center',
          }}
        >
          {brand.company_name || ''}
        </AbsoluteFill>
      );
    }
  }
};
